// @ts-nocheck
/* mockoon-gen-sha256: 87682626878ca5246fcd4b899916b8c67250ef83b5c942c41fa745b21e555582 */
/* eslint-disable */
/* This file is generated by mockoon-gen. Do not edit by hand unless you accept it back into the artifact workflow. */
declare function request<T>(
  path: string,
  options?: { method?: string; body?: unknown },
): Promise<T>;

export interface GetSkuAvailableWarehousesResponseDTO {}
export interface GetSkuAvailableWarehousesVO {}
export function toGetSkuAvailableWarehousesVO(
  dto: GetSkuAvailableWarehousesResponseDTO,
): GetSkuAvailableWarehousesVO {
  const vo = {} as GetSkuAvailableWarehousesVO;
  return vo;
}
export async function getSkuAvailableWarehouses(
  skuId: string | number,
): Promise<GetSkuAvailableWarehousesVO> {
  const path = `/api/skus/${encodeURIComponent(String(skuId))}/available-warehouses`;
  const dto = await request<GetSkuAvailableWarehousesResponseDTO>(path, { method: 'GET' });
  return toGetSkuAvailableWarehousesVO(dto);
}
export interface ListOutboundOrdersResponseDTO {}
export interface ListOutboundOrdersVO {}
export function toListOutboundOrdersVO(dto: ListOutboundOrdersResponseDTO): ListOutboundOrdersVO {
  const vo = {} as ListOutboundOrdersVO;
  return vo;
}
export async function listOutboundOrders(): Promise<ListOutboundOrdersVO> {
  const dto = await request<ListOutboundOrdersResponseDTO>('/api/outbound-orders', {
    method: 'GET',
  });
  return toListOutboundOrdersVO(dto);
}
export interface CreateOutboundOrderResponseDTO {}
export interface CreateOutboundOrderVO {}
export function toCreateOutboundOrderVO(
  dto: CreateOutboundOrderResponseDTO,
): CreateOutboundOrderVO {
  const vo = {} as CreateOutboundOrderVO;
  return vo;
}
export async function createOutboundOrder(): Promise<CreateOutboundOrderVO> {
  const dto = await request<CreateOutboundOrderResponseDTO>('/api/outbound-orders', {
    method: 'POST',
  });
  return toCreateOutboundOrderVO(dto);
}
